"""empty message

Revision ID: 5fede78234a7
Revises: 
Create Date: 2020-05-31 15:19:09.248937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fede78234a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customer', sa.Column('personal_discount', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('total', sa.Float(), nullable=True))
    op.drop_index('slug', table_name='customer')
    op.drop_column('customer', 'slug')
    op.add_column('product', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'price')
    op.add_column('customer', sa.Column('slug', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('slug', 'customer', ['slug'], unique=True)
    op.drop_column('customer', 'total')
    op.drop_column('customer', 'personal_discount')
    op.drop_table('sale')
    # ### end Alembic commands ###
